-- General Manager must see all reports. computed_pnl / report_ranges / support
-- tables already grant GM read; this adds GM read to the truck / GFFC / company /
-- raw monthly / parameters / ROI data tables (finance keeps write; GM read-only).
drop policy if exists "bu_parameter_std_gm" on public.bu_parameter_std;
create policy "bu_parameter_std_gm" on public.bu_parameter_std for select using (public.current_role() = 'gm');
drop policy if exists "bu_parameters_gm" on public.bu_parameters;
create policy "bu_parameters_gm" on public.bu_parameters for select using (public.current_role() = 'gm');
drop policy if exists "bu_pnl_config_gm" on public.bu_pnl_config;
create policy "bu_pnl_config_gm" on public.bu_pnl_config for select using (public.current_role() = 'gm');
drop policy if exists "expense_account_sections_gm" on public.expense_account_sections;
create policy "expense_account_sections_gm" on public.expense_account_sections for select using (public.current_role() = 'gm');
drop policy if exists "gffc_branch_pnl_gm" on public.gffc_branch_pnl;
create policy "gffc_branch_pnl_gm" on public.gffc_branch_pnl for select using (public.current_role() = 'gm');
drop policy if exists "gffc_monthly_expense_gm" on public.gffc_monthly_expense;
create policy "gffc_monthly_expense_gm" on public.gffc_monthly_expense for select using (public.current_role() = 'gm');
drop policy if exists "gffc_monthly_pnl_gm" on public.gffc_monthly_pnl;
create policy "gffc_monthly_pnl_gm" on public.gffc_monthly_pnl for select using (public.current_role() = 'gm');
drop policy if exists "gffc_monthly_sales_gm" on public.gffc_monthly_sales;
create policy "gffc_monthly_sales_gm" on public.gffc_monthly_sales for select using (public.current_role() = 'gm');
drop policy if exists "import_batches_gm" on public.import_batches;
create policy "import_batches_gm" on public.import_batches for select using (public.current_role() = 'gm');
drop policy if exists "item_units_gm" on public.item_units;
create policy "item_units_gm" on public.item_units for select using (public.current_role() = 'gm');
drop policy if exists "monthly_bu10_salary_gm" on public.monthly_bu10_salary;
create policy "monthly_bu10_salary_gm" on public.monthly_bu10_salary for select using (public.current_role() = 'gm');
drop policy if exists "monthly_bu_alloc_gm" on public.monthly_bu_alloc;
create policy "monthly_bu_alloc_gm" on public.monthly_bu_alloc for select using (public.current_role() = 'gm');
drop policy if exists "monthly_company_pnl_gm" on public.monthly_company_pnl;
create policy "monthly_company_pnl_gm" on public.monthly_company_pnl for select using (public.current_role() = 'gm');
drop policy if exists "monthly_expense_gm" on public.monthly_expense;
create policy "monthly_expense_gm" on public.monthly_expense for select using (public.current_role() = 'gm');
drop policy if exists "monthly_pnl_inputs_gm" on public.monthly_pnl_inputs;
create policy "monthly_pnl_inputs_gm" on public.monthly_pnl_inputs for select using (public.current_role() = 'gm');
drop policy if exists "monthly_pnl_pools_gm" on public.monthly_pnl_pools;
create policy "monthly_pnl_pools_gm" on public.monthly_pnl_pools for select using (public.current_role() = 'gm');
drop policy if exists "monthly_sales_gm" on public.monthly_sales;
create policy "monthly_sales_gm" on public.monthly_sales for select using (public.current_role() = 'gm');
drop policy if exists "monthly_truck_expense_gm" on public.monthly_truck_expense;
create policy "monthly_truck_expense_gm" on public.monthly_truck_expense for select using (public.current_role() = 'gm');
drop policy if exists "monthly_truck_income_gm" on public.monthly_truck_income;
create policy "monthly_truck_income_gm" on public.monthly_truck_income for select using (public.current_role() = 'gm');
drop policy if exists "monthly_truck_inputs_gm" on public.monthly_truck_inputs;
create policy "monthly_truck_inputs_gm" on public.monthly_truck_inputs for select using (public.current_role() = 'gm');
drop policy if exists "monthly_truck_salary_gm" on public.monthly_truck_salary;
create policy "monthly_truck_salary_gm" on public.monthly_truck_salary for select using (public.current_role() = 'gm');
drop policy if exists "monthly_trucking_gm" on public.monthly_trucking;
create policy "monthly_trucking_gm" on public.monthly_trucking for select using (public.current_role() = 'gm');
drop policy if exists "pivot_accounts_gm" on public.pivot_accounts;
create policy "pivot_accounts_gm" on public.pivot_accounts for select using (public.current_role() = 'gm');
drop policy if exists "pivot_snapshots_gm" on public.pivot_snapshots;
create policy "pivot_snapshots_gm" on public.pivot_snapshots for select using (public.current_role() = 'gm');
drop policy if exists "pivot_values_gm" on public.pivot_values;
create policy "pivot_values_gm" on public.pivot_values for select using (public.current_role() = 'gm');
drop policy if exists "pnl_months_gm" on public.pnl_months;
create policy "pnl_months_gm" on public.pnl_months for select using (public.current_role() = 'gm');
drop policy if exists "roi_labor_manual_gm" on public.roi_labor_manual;
create policy "roi_labor_manual_gm" on public.roi_labor_manual for select using (public.current_role() = 'gm');
drop policy if exists "support_unit_config_gm" on public.support_unit_config;
create policy "support_unit_config_gm" on public.support_unit_config for select using (public.current_role() = 'gm');
